site_name: Dataview Example Vault
repo_url: https://github.com/s-blu/obsidian_dataview_example_vault
docs_dir: pages

theme:
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 