site_name: Dataview Example Vault
repo_url: https://github.com/s-blu/obsidian_dataview_example_vault
docs_dir: pages

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple

markdown_extensions:
    - toc:
         permalink: True
    - fenced_code
    - tables
    - admonition
    - meta
    - nl2br

plugins:
  - search
  - roamlinks 